#!/bin/bash

#adb shell input keyevent 82
#log.newline "powering on phone"
#adb shell input keyevent 26 # doesn't work to start the s4
#log.ok
log.newline "installing"
adb install -r bin/OldCam-debug.apk 2>/dev/null >/dev/null
log.ok
#adb logcat -c 2>/dev/null >/dev/null
log.newline "starting"
adb shell am start -n com.jimi.oldcam/.MainActivity 2>/dev/null >/dev/null
log.ok
#adb logcat *:S Courses:I &
#pid=$!
#read s
#log.newline "closing adb $pid"
#kill $pid
#log.ok
#log.newline "shutting down phone"
#adb shell input keyevent 26  # damn s4
#log.ok
